### ISSUE TITLE
Error template in gcc 4.9

### ISSUE THREAD

**Issue by makiolo** [jbandela/stackless_coroutine#1]
Hello,

Congratulations for your stackless implementation, is very nice and interesting for me. I have a problem when compile in gcc 4.9 (works in clang 3.6):

/home/travis/build/makiolo/asyncply/stackless_coroutine/stackless_coroutine.hpp:223:16: error: template declaration of ‘constexpr const bool stackless_coroutine::detail::has_finished_storage_v’ ([Travis source](https://travis-ci.org/makiolo/asyncply/jobs/172560745))

Thanks. Ricardo.

**Comment by jbandela** [comment]
GCC 4.9 has enough template bugs that it is unsupported.
